dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.7"

install:
  - pip install numpy
  - pip install soundfile
  - python setup.py install

script: cd samples && python sample.py
